version: '3'

services:
  auth-service:
    build: ./services/auth_service/
    ports:
      - 8000:8000
    depends_on:
      - db-users
  
  folder-service:
    build: ./services/folder_service/
    ports:
      - 8001:8001
    depends_on:
      - db-folders

  structurizr:
    image: structurizr/lite 
    ports:
      - 9999:8080
    volumes:
      - .:/usr/local/structurizr:z

  db-folders:
    image: postgres:14
    volumes:
      - ./db/folders/data:/var/lib/postgresql/data
      - ./db/folders/init:/docker-entrypoint-initdb.d
    restart: always
    environment:
      POSTGRES_DB: db-folders
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - 5433:5432
    
  db-users:
    image: postgres:14
    volumes:
      - ./db/users/data:/var/lib/postgresql/data
      - ./db/users/init:/docker-entrypoint-initdb.d
    restart: always
    environment:
      POSTGRES_DB: db-users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
