global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8000']

  - job_name: 'folder-service'
    static_configs:
      - targets: ['folder-service:8000']

  - job_name: 'email-service'
    static_configs:
      - targets: ['email-service:8000']