scrape_configs:
  - job_name: 'auth-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['auth-service:8000']
  - job_name: 'folder-service'
    static_configs:
      - targets: ['folder-service:8000']
  - job_name: 'email-service'
    static_configs:
      - targets: ['email-service:8000']